[package]
name = "tentacle-multiaddr"
version = "0.1.0"
authors = ["driftluo <driftluo@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unsigned-varint = "0.2.2"
bytes = "0.5"
bs58 = "0.3.0"
sha2 = "0.8.0"
serde = "1"

[dev-dependencies]
parity-multiaddr = "0.4"
