[package]
name = "tentacle-discovery"
version = "0.2.5"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
license = "MIT"
description = "p2p discovery protocol main reference bitcoin"
keywords = ["network", "peer-to-peer", "p2p", "discovery"]
repository = "https://github.com/nervosnetwork/p2p"
categories = ["network-programming", "asynchronous"]
edition = "2018"

[dependencies]
p2p = { path = "../..", version = "0.2.0", package = "tentacle" }
bytes = "0.4"
byteorder = "1.2"
futures = "0.1"
tokio = "0.1"
log = "0.4"
rand = "0.6.1"
flatbuffers = "0.6.0"
flatbuffers-verifier = "0.2.0"

[dev-dependencies]
env_logger = "0.6"
